# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad0cc60209d664a055de888c076e9b5c9b9f1fe466e912e03b8da1f18a609b39d89f268ef965a9a286df785956cfa8f1ac07e3a389691d3e57905ed2188327a9

test:
  secret_key_base: f6e575f2d4228f484ccdcbf87ddefd2ee8d477f7ec81afc24e15e6d26e2c267ef9a0755f3e825fc2fb57bb4f6bdd1db5a8bbe869fcbd8f111316b7a091205c43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
